language: python
python:
  - "2.7"
  - "3.3"
install:
 - pip install --allow-external PyZenity --allow-unverified PyZenity -r requirements.txt --use-mirrors
script: python -m unittest discover worklogger '*_test.py'
